-- Eliminamos previamente los sinonimos
DROP SYNONYM LOG;
DROP SYNONYM USERS;
DROP SYNONYM ADMINISTRADORES;
DROP SYNONYM EQUIPOS;
DROP SYNONYM JUGADORES;
DROP SYNONYM DUENIOS;
DROP SYNONYM ASISTENTES;
DROP SYNONYM JORNADAS;
DROP SYNONYM CLAS;
DROP SYNONYM PARTIDOS;
DROP SYNONYM ENTRENADORES;

-- Creación de sinonimos
CREATE OR REPLACE PUBLIC SYNONYM LOG FOR EQDAW04.LOGIN;
CREATE OR REPLACE PUBLIC SYNONYM USERS FOR EQDAW04.USUARIO;
CREATE OR REPLACE PUBLIC SYNONYM ADMMINISTRADORES FOR EQDAW04.ADMINISRADOR;
CREATE OR REPLACE PUBLIC SYNONYM EQUIPO FOR EQDAW04.EQUIPO;
CREATE OR REPLACE PUBLIC SYNONYM JUGADORES FOR EQDAW04.JUGADOR;
CREATE OR REPLACE PUBLIC SYNONYM DUENIOS FOR EQDAW04.DUENO;
CREATE OR REPLACE PUBLIC SYNONYM ASISTENTES FOR EQDAW04.ASISTENTE;
CREATE OR REPLACE PUBLIC SYNONYM JORNADAS FOR EQDAW04.JORNADA;
CREATE OR REPLACE PUBLIC SYNONYM CLAS FOR EQDAW04.CLASIFICACION;
CREATE OR REPLACE PUBLIC SYNONYM PARTIDOS FOR EQDAW04.PARTIDO;
CREATE OR REPLACE PUBLIC SYNONYM ENTRENADORES FOR EQDAW04.ENTRENADOR;

-- Creación de vistas
-- Con esta vista somos capaces de ver la clasificación de la liga en orden
DROP VIEW VerClasificacion;

CREATE VIEW VerClasificacion AS
SELECT e.Nombre, c.Puntos, c.Temporada
FROM CLASIFICACION c, EQUIPO e
WHERE c.id_equipo = e.id_equipo
ORDER BY c.Puntos DESC;

-- Para comprobar:
SELECT * FROM VerClasificacion;

-- Visualizamos toda la información de todos los equipos
DROP VIEW VerEquipos;

CREATE VIEW VerEquipos AS
SELECT p.Nombre AS "Nombre", p.ano_creacion AS "AÑO", p.nacionalidad AS "NACIONALIDAD", d.nombre AS "DUENO", a.nombre AS "ASISTENTE", e.nombre AS "ENTRENADOR" 
FROM EQUIPO p, DUENO d, ASISTENTE a, ENTRENADOR e
WHERE p.ID_DUENO = d.ID_DUENO AND p.ID_ASISTENTE = a.ID_ASISTENTE AND p.ID_ENTRENADOR = e.ID_ENTRENADOR ORDER BY ID_EQUIPO ASC;

-- Para comprobar:
SELECT * FROM VerClasificacion;

COMMIT;